<!--Copyright (C) $today.year  深圳极向量科技有限公司 All Rights Reserved.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.neatlogic</groupId>
        <artifactId>neatlogic-parent</artifactId>
        <version>[3.0.0, 4.0.0)</version>
    </parent>
    <artifactId>neatlogic-webroot</artifactId>
    <packaging>war</packaging>
    <version>3.0.0</version>
    <profiles>
        <profile>
            <id>commercial</id>
            <dependencies>
                <!--<dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-master</artifactId>
                </dependency>-->
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-codehub</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-codehub-base</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-rdm-commercial</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-cmdb-commercial</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-document-online-commercial</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-dr</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-dr-base</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-diagram</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-eoa</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-eoa-base</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-pbc</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-itsm-commercial</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-tenant-commercial</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-database</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-alert</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.neatlogic</groupId>
                    <artifactId>neatlogic-alert-base</artifactId>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
    <build>
        <finalName>neatlogic</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.2.2</version>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-tenant</artifactId>
        </dependency>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-dashboard</artifactId>
        </dependency>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-itsm</artifactId>
        </dependency>

        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-change</artifactId>
        </dependency>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-report</artifactId>
        </dependency>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-event</artifactId>
        </dependency>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-knowledge</artifactId>
        </dependency>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-autoexec</artifactId>
        </dependency>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-cmdb</artifactId>
        </dependency>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-tagent</artifactId>
        </dependency>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-inspect</artifactId>
        </dependency>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-deploy</artifactId>
        </dependency>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-rdm</artifactId>
        </dependency>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-document-online</artifactId>
        </dependency>
        <dependency>
            <groupId>com.neatlogic</groupId>
            <artifactId>neatlogic-resources</artifactId>
        </dependency>
    </dependencies>
</project>
