#
# Copyright(c) 2023 NeatLogic Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#database properties
db.driverClassName = com.mysql.cj.jdbc.Driver
#db.url = jdbc:mysql://localhost:3306/neatlogictlcb?characterEncoding=UTF-8&jdbcCompliantTruncation=false&allowMultiQueries=true&useSSL=false&&serverTimeZone=Asia/Shanghai
db.url = jdbc:mysql://localhost:3306/neatlogic?characterEncoding=UTF-8&jdbcCompliantTruncation=false&allowMultiQueries=true&useSSL=false&&serverTimeZone=Asia/Shanghai
#db.url = jdbc:mysql://localhost:3306/neatlogiccommunity?characterEncoding=UTF-8&jdbcCompliantTruncation=false&allowMultiQueries=true&useSSL=false&&serverTimeZone=Asia/Shanghai
#db.url = jdbc:mysql://192.168.3.25:3306/neatlogic?characterEncoding=UTF-8&jdbcCompliantTruncation=false&allowMultiQueries=true&useSSL=false&&serverTimeZone=Asia/Shanghai
#db.url = jdbc:mysql://localhost:3306/neatlogicos?characterEncoding=UTF-8&jdbcCompliantTruncation=false&allowMultiQueries=true&useSSL=false&&serverTimeZone=Asia/Shanghai
#db.url = jdbc:mysql://192.168.0.94:3306/neatlogic?characterEncoding=UTF-8&jdbcCompliantTruncation=false&allowMultiQueries=true&useSSL=false&&serverTimeZone=Asia/Shanghai
#db.url = jdbc:mysql://192.168.0.92:3306/neatlogic?characterEncoding=UTF-8&jdbcCompliantTruncation=false&allowMultiQueries=true&useSSL=false&&serverTimeZone=Asia/Shanghai
#db.url = jdbc:mysql://192.168.1.135:3306/neatlogicos?characterEncoding=UTF-8&jdbcCompliantTruncation=false&allowMultiQueries=true&useSSL=false&&serverTimeZone=Asia/Shanghai
#db.url = jdbc:mysql://192.168.1.135:3306/neatlogic?characterEncoding=UTF-8&jdbcCompliantTruncation=false&allowMultiQueries=true&useSSL=false&&serverTimeZone=Asia/Shanghai
db.username = root
#db.password = Zanyue$2022
db.password = zanyue$2012
#db.password = neatlogic@901
#db.password = {RC4}9742fce09d8b8186958330
#db.password = hkfsHIsvwL123
db.dataSource.maxTotal=10

conn.validationQuery = select 1
conn.testOnBorrow = true
conn.maxActive = 50
conn.initialSize = 4
conn.maxIdle=16

server.host=http://192.168.0.25:8282

minio.url = http://192.168.1.125:8989
minio.accesskey = minioadmin
minio.secretkey = minioadmin

home.url = http://localhost:8081/
master.home.url = http://localhost:9099/
is.maintenance.mode = true

jms.url = tcp://localhost:61616
jms.user = cocokong
jms.password = 123456Ab1

mongo.host=192.168.1.140:27017,192.168.0.26:27017,192.168.0.21:27017
mongo.port=27017
mongo.username=admin
mongo.password=zanyue$2012
mongo.database=admin

wechat.corp.id = wx8a4c400b4c54eead
wechat.app.secret = YWKdMPnTeXQusTqpx6gQgkgbrBqc73RzGyvVOrxflcQ
wechat.app.agent.id = 1000015

mobile.is.online = true

heartbeat.rate = 3
heartbeat.threshold = 5

license.pk = MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHfhFEod4K3VlDdF0zGFLeavGyokUt/Njczl/4yAwpOvTUNW0x3C4Uc49NjP3Vr8KYYbsXk7DKv+8hoENGfltSzepmPpX4Mu+iclUqyaLbLHoX+rB7SagjiekuG3B1/ADPLsuG6VFkC00yEFkMUmZhU5IVbTTTKEpCtH8bJxa1aQIDAQAB
#??
#license = jmzrFigbv6M4JZu+XbVmo1OQZOYpeZD3XcCnPIrJ4x3/r1UhwbnuA9MI6ekJQ8Yqw0ki/3dJ5cZQ9tpbgjYHGvfgCe1h/FAshKlRxFqTTnoicfaapO7Qsz5ZeN/sGv8C6LiivdR7HDThUwcEtrEz2kJqmDbKqVcMZCgvvBrupqwgujMh3NecMnAZLdef+c47acwwpuo+4brgwzkuUZueB09qpRdLmGnUgbMrciW5Uqo2pMEgkc6AwKhXVTZ0PNdqaqQZGQyJy6nOso2OFe5RcZWj9gUnLDP9OPMAXEqIeRey4HH9vs4IjTdOzXvefg8mBFZwq0+PsygzHRkyg+4rs5chmlc43cr/ytqTa8xk6VO5tSI0kB0KC5pNMS1dOY1ITIhl3gUuSfkeuM0af17gmhZyUWEqiVMSczpAEKC/TlAvi4CL51DMU8FrUWgEvABjIauy4PwGabR1PaJCoaKcQRSjefaxkKcBsdVUp3JE2Yu+jJi8I3kuoI/zN+tnAJIogNlvr4QdMoKKDvB1x5OqSmB+rTy21BZp8g5kdUJtv3+GUQcR2s5GtRSW3ryDxMdocl0tJGpK9Z9fV5hHSr8Wks47DqEQWVusDGQXwA9mpxfGCSiXUn5xcaDl74onM0jgrUsSV4bF/NRecf2FeEgVuzxKv/Be6cBykY8pwrBOPS0K2CGUS77Oavxxpg7TQDnq5izo6DONcQTTFnKj7+sL8kVkZngfSjg7E6ZK9yWiLm19AmL1ZrOxxcAJEfXUhfi8G00THYgD0FPsMpV5bEWA7M6z25dHaB9Il9OGLNhpdKpHBGK6zWswJ3SfWEFUZoZAjaRSTc5H5R7W0JjmD6Nx8Q==#fh24euV/54kntcXyPpeR0/Kv2v9FRs320QX9sV/PyJh35Ix/pctcxkmNOJ1VLQz+QGrZWoe4igDteIDalJlqAZvxY+iLQHf5x+Ih0y0m5ekeCRpqmHPLYVyDxazQeXH7k9wKJAZZKjqZgLF/6S3PjEGD9ZJHGEHSWHDW3XCAMcE=
#??
license = wb89Fzv6KEHdixlPP7/44lrQapnpnJVQk6awoD/cJkSz9fMrKRGNtXXzZOZx0rUoZPsnm+DoTi8MW/nIBFZOEcdZ48w+CHwHQI3MlvSEUEquqSsgXBPfMVpryDHWF12CFFLbJ008ZktDRW2pSWECJWpo7BL9zAzD6sD3pDuxeqha6J1jyhsjekpQPqjm+JOgeuYj0+pE4Zi+UfKjDW9naMm/jIxkF3wz9gvnZAJG8r9fv0OJkhcJrf/IlKWHfKYmaUGwyIG96Zu3x07whIHS7Ct41aYcTTsAzyGMdMXoMnuhOYgTXv98eaWvMxy0ckE4mMs5ryuwbvgmUbSLEAHCKhjrwq6ma0dXy2/8svcwhT5wAcWVe0/Qdg9i1NVSlde72lNRggWl0yQAaUaZuGLkLq/3gdqZQi8fElHjpmf2SRBC2EeHuci/rR//V9DW+oX0qrGY/abl/zm2RUdbEVXhAyzcgzeBc7wPDbvVt0v+TZGI55whlvncVh/VARVeZ7RvtROYPKGA3xeOZZ9A937bsjLoFXpOSbcvZA4On44gSi77+YZFzR+J6ZKAZbAg+z39nftoVBxY7O3Q7Xui/7mCx/NT5mplbaM6mNRYXL2ZTGISj7Yca4L00Bw3gRcLWCYqAGpOdNkRJ87q5d8MOfg12CSSlFVzfbyyjn5kclbKiIwHgOtFBQPyLZw/dVX/fj4txK/O60F2Km9EWT0NZ0euFoUYutIQQR8dym4JypvU/krIG7EaC434gXhqZDdohjQ8po48ONFrBi/aHXtTmdPgkHDHigVJBB3blT4R45uyo7bCLKYDn6L4/bF3Tzpdn4l802U7BxYa42twyTZ34mQ34arjgDfFp0UmoEF7NNC1rwG9pPg2cTRn1y02D4Mt9ft9paNA8HcFCM3y+q9bttZ0+WxDPEui9UFWoeyGcBnQkzSbTt0Fv7XtOOJrD3Ep2JPZDYeggZZCNhbjYME34ZYhe7OVWon6orRrzmxVUnCDfjZAvatJKyVKf730xkZl0syMGsGgbTIrqHEjYSvTYN13kk93ST5f+BX65NbchhJCx3W+2/ABTkPDCwyBwlSzM7wZRUmafmcRAaBBSZpaHIe+yaDTETC/5G4NxXAgqF5yDt0CaB1jq3poVhPcQk4LYg9TSBPUkGbcZALZdbhvoR9GBF4hAT0LjXUCR+MVIL8J9ZSTVkY324TPPbtYmtwlXZ7STBlSOyWZ/pbPEMoRQKGacHSJY4Oq0n1CyqgvrbA1uiSZ2NQDczBWw4zoA89z9B/wWbnkKQXywmasMJyXsdUNov/LPpScakFmRI13+Q7FSuxftSStkuF/qK60aV/d/lHdgpqUxkpzXre12Cdz4Kc2l0HgGKBa09Y0zy1RIp7Kj/Eao6EARclH+/n7g5yMFzx4V5/SyfhOfv7pv4gsGaFiTzhAOdj1dWfiFJY4rEeARoWuPS1aDEl6azqFu6pXLVGffbcKNnpwUCxspqn/TCrYjBlUtD0OUhJoQoVJIXvyW75cH6aH5eNSc0WTKys25i6Mw0VXYBPsIOJ7I9/6ZIoOt9cGbf33nZNswd7UctPH1zWbRXDX02rXP64gMD8udePB/nbbSiFDMtIyn0e1Lz0DhF1F+PUbZ4ZQSrX9N5JTx/dAJFOCjLryUp7pzfrXuQajyBdqqarqlO/ni/RSoeV06/xl+bChUxr9G/GqCMZpF+QVFRzqiWojepOz8IENZugwsURkL+ZO5ZHvKEwWuHIMDZfIs04TYpBzxm9Qp+n8CM6x/zycYjXX2tVMsecj2SG2nHls3JYd0VHNh0AxVr4gd5sUEjhAviDTsM8gyLDOqiz4+1bnK1uQ/4QSAPELM7DE/9+gfVPQpo68mqKSi8qOEEsgeDYa+hFAzYuji8JXZlIw2So7aQUiS2aP78GdkYeILIf29jNDDRgiKWBiqUQE+mu/78t3pQwUJY8X75vP86SPwOaPaMkzAOwNOTkLD4j0f9XIwlAfLbThXAZkEkzK3j8gqy/7ngJW4Tav1EJCqkRXJr0mDGkcgBN5VQW8t7/1mWzIv35gjGNvuAg/JJTTUSSWqxfkxcRz7JvCODJ+LZZ3gPf/N2N41X+fjpDtlIwwU1iHe1M3LVC0HSHUlYJL+NlIkiHf1z/AT/xqa6TWwxQrsIywhVU3JtuMt2+vq1Epudkl5rUFehERIP1N2KOLU/ED54Dmi+eXZXxewVrQlPAbtnWzZgyz6ij1kysrLdFByErknBTa6x2TueP3Xvp2JvHcfNU5j/mDH+OkIiKqErmN4b92PGtrOnBGGF73il2IGlrcf7nWBx01iGTYwFkmQh1bDSc1GWR13Mj4LDezUHY1KL6WVhbJC4w5gcSnk1RbstoXaIsGQlAy/rKcrCZJK4RsQG1QoPlUg6AuEyA3qs6DNuJSQd3QtwwCueYpDu+vobv66z+k2MphmXjzJt6lG6WzjngcEww7sWYGfEl8IpmZDADekNkfGT5+3qUTPMxF+5hCiUAIcOhC5cKulgTrvNo6j1V9ChyzGurv6gwg9ffqiXBLJI0jPwSW6meHz45HAWUeI75KPrd+nQr+1Shbt4F8jlAzPI2Z38wdb6PE4TMxG9lzMPJYNcCjF9Q/dZeA9rOGM+5ch17+VMyeZqBMx1LAtBiUZn5KkYHLMk1gukvY0Ec4QXnR5fc6tAUMUEMa//vvN1t5KHgjPRBR1QLd+Ylq/8Ea+ZMzXcBCtLV389cZVVlG9cFpM9+KLs1Y3APUXoDopaM4dW1hDYGLD2p9VdS0uFiwyD9JtJe6IEA3DlKdjFBvybsI2Z/Lfn3LS8SANa7SmrMVoMI0QPYb2tmnxJgLHSrBdrCWtwCg5zseXi6+V/496gSycD6wfTV4oTLhS9EnqroqawEvi2xAfFxJWrmW7/pmESlSsttBM4HR9IV5caxfX7MWhPKvEln3/i53obDWSTaL/DZ61LYUP16aYIaNWukZRfxAApm1zvU6WqtkvjwS8NIwPQHhklxzk+l1YQpJIZIu1yZY1T5lPLzYwzkcrml0Rhon6+wWhcO8fWSU2avnvDQN48k0bu983XG3#bck6x4/7jxUX471+Jx6P4qt6T+tZI7Vi8zYMihbR79G6RbtwaBF62zqbEjfIlrlVzlcpVuHDGeRIRmf9UbIOu/O2MUypvHVV/lyOqg5dHLwuKh7UWB1i6AiJ5qYKQh8Mje8RqZ96XyaZxFDZngrluz39V0LLLpaeAuZWzc5S6Xc=
direct.url =
sso.ticket.key =

sso.user.unique.key = id
sso.auth.login.url = www.baidu.com
sso.user.get.url = www.bb.com


data.home = /Users/cocokong/tmp

tenant.limit.count = 10

tenant.limit.day = 3

#??????
maintenance = neatlogic
#??????
maintenance.password = 123456


runner.host = localhost

autoexec.token = 499922b4317c251c2ce525f7b83e3d94

#ldap.server.url = ldap://192.168.1.99:389
#login.auth.type = 4a
#ldap.user.dn = cn={0},ou=ts,dc=techsure,dc=com
#login.auth.password.encrypt=base64
#sso.ticket.key = tgt

mobile.direct.url=/loginerror
mobile.logout.url=/loginout


report.jdbc.query.timeout=1